### ISSUE TITLE
penthouse 1.0 run test-all failed in 5 test

### ISSUE THREAD

**Issue by hummal** [pocketjoso/penthouse#180]
Not sure if this is a OS dependency but on following specs using "npm run test-all" 5 tests are failing.

Windows 7 Pro x64
nodejs 8.2.1
npm 5.3.0

**Comment by pocketjoso** [comment]
Can you share what tests failed? I can imagine that the tests that check whether puppeteer closed the headless chrome instance or not will fail, as it uses simple `ps aux` regexes, that probably need to be updated for Windows. I'm interested to know what other tests failed though.

**Comment by hummal** [comment]
Sure:
`
1) extra tests for penthouse node module error should handle parallell jobs, sharing one browser instance, closing afterwards:
     Uncaught Error: spawn egrep ENOENT
      at exports._errnoException (util.js:1024:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
      at onErrorNT (internal/child_process.js:374:16)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) extra tests for penthouse node module should keep chromium browser instance open, if requested:
     Uncaught Error: This socket is closed
      at Socket._writeGeneric (net.js:721:18)
      at Socket._write (net.js:781:8)
      at doWrite (_stream_writable.js:371:12)
      at writeOrBuffer (_stream_writable.js:357:5)
      at Socket.Writable.write (_stream_writable.js:274:11)
      at Socket.write (net.js:699:40)
      at Socket.<anonymous> (D:/Repositories/penthouse/test/node-module-tests.js:104:51)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:252:12)
      at readableAddChunk (_stream_readable.js:239:11)
      at Socket.Readable.push (_stream_readable.js:197:10)
      at Pipe.onread (net.js:589:20)

  3) penthouse fault tolerant normalising css tests should generate same layout for yeoman with css errors:
     Error: Error: ENOENT: no such file or directory, open 'D:\Repositories\penthouse\test\results\yeoman-before.jpg'
      at D:/Repositories/penthouse/lib/index.js:265:23
      at Generator.next (<anonymous>)
      at step (D:/Repositories/penthouse/lib/index.js:45:183)
      at D:/Repositories/penthouse/lib/index.js:45:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

 4) penthouse fault tolerant normalising css tests should correctly AST parse css with extra closing braces w/o dropping rules:
     Uncaught Error: spawn egrep ENOENT
      at exports._errnoException (util.js:1024:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
      at onErrorNT (internal/child_process.js:374:16)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  5) penthouse fault tolerant normalising css tests "after all" hook:
     Uncaught Error: This socket is closed
      at Socket._writeGeneric (net.js:721:18)
      at Socket._write (net.js:781:8)
      at doWrite (_stream_writable.js:371:12)
      at writeOrBuffer (_stream_writable.js:357:5)
      at Socket.Writable.write (_stream_writable.js:274:11)
      at Socket.write (net.js:699:40)
      at Socket.<anonymous> (D:/Repositories/penthouse/test/node-module-tests.js:137:49)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:252:12)
      at readableAddChunk (_stream_readable.js:239:11)
      at Socket.Readable.push (_stream_readable.js:197:10)
      at Pipe.onread (net.js:589:20)
`

**Comment by pocketjoso** [comment]
Thanks. So Penthouse would ideally get a fix for this, but it is not high prio, and I don't have access to any windows environment. So PR's welcome!

**Comment by bezoerb** [comment]
I've added a PR to add appveyor tests (windows) to penthouse: https://github.com/pocketjoso/penthouse/pull/183

**Comment by pocketjoso** [comment]
Thanks @bezoerb. Makes most sense to me to fix the windows issues before/at the same time as adding the windows testing . I'll try to find time for it, but as I said it's not the highest priority for me right now. I would love a PR for this.

Main problem seems to be the usage of `spawn` (for which I think there's a cross-platform spawn lib), but I think there will be a few other crashes, like `ps aux` process regexes that I mentioned before.

**Comment by Saturate** [comment]
Use https://ci.appveyor.com/ for the windows build/testing, works great with Travis. Puppeteer uses the same CI, and I've used it a lot for windows.
