### ISSUE TITLE
Unhandled rejection Error: css should not be empty

### ISSUE THREAD

**Issue by shervud** [pocketjoso/penthouse#230]
Hi, @pocketjoso 
Firstly, thank you for the great lib!
I've faced with an ugly issue "Unhandled rejection Error: css should not be empty".
This issue appears only on URLs whose <html> body does not have any css includings such as: <link href="url-to-css.css" />.
Some URLs implement css sources includings in the following way:
<style>
@import('url-to-css.css');
</style>
And it seems critical and penthouse modules libs ignore such files.

So, if some site has the next html:
`
<html>
<head>
<style>@import('http://example.com/styles/my-style.css');</style>
<link href="http://example.com/styles/my-prints.css" media="print" />
</head>
<body>...</body>
</html>
`
It will never work. While the following implementation will work:
`
<html>
<head>
<link href="http://example.com/styles/my-style.css" media="all" />
<link href="http://example.com/styles/my-prints.css" media="print" />
</head>
<body>...</body>
</html>
`

`Unhandled rejection Error: css should not be empty
    at node_modules/penthouse/lib/index.js:308:33
    at Generator.next (<anonymous>)
    at step (node_modules/penthouse/lib/index.js:45:191)
    at node_modules/penthouse/lib/index.js:45:437
    at new Promise (<anonymous>)
    at node_modules/penthouse/lib/index.js:45:99
    at Promise (node_modules/penthouse/lib/index.js:325:20)
    at new Promise (<anonymous>)
    at module.exports (node_modules/penthouse/lib/index.js:269:10)
    at node_modules/critical/lib/core.js:170:16
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:454:14)
    at ReductionPromiseArray._resolve (node_modules/bluebird/js/release/reduce.js:61:19)
    at ReductionPromiseArray._resolveEmptyArray (node_modules/bluebird/js/release/reduce.js:52:10)
    at ReductionPromiseArray.init (node_modules/bluebird/js/release/promise_array.js:71:18)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)`

There is the same issue described https://github.com/addyosmani/critical/issues/277

**Comment by pocketjoso** [comment]
Thanks - this is indeed an issue for critical - `Penthouse` requires you to pass it `css`, otherwise the library cannot do the critical css generation.

**Comment by shervud** [comment]
Thank you for the answer

**Comment by pocketjoso** [comment]
FYI my paid https://criticalcss.com service handles this correctly - But I
also imagine that critical the lib will be able to fix it quite easily.

Le 16 févr. 2018 11:23, "Ihar Piniazkou" <notifications@github.com> a
écrit :
