### ISSUE TITLE
Error while in strict mode

### ISSUE THREAD

**Issue by ChristianLJ** [pocketjoso/penthouse#239]
This might not be related to penthouse but i am not sure.

I get the following error when compiling with strict mode set to true.

The wrong CSS seems to be a part of bootstrap but i don't get why it is wrong? 

Can someone please elaborate?

```
----------------------------------------------------------------^
    at ´...\node_modules\penthouse\lib\index.js:143:13
    at Generator.next (<anonymous>)
    at step (...\node_modules\penthouse\lib\index.js:45:191)
    at ...\node_modules\penthouse\lib\index.js:45:437
    at Promise (<anonymous>)
    at ...\node_modules\penthouse\lib\index.js:45:99
    at astFromCss (...\node_modules\penthouse\lib\index.js:152:18)
    at ...\node_modules\penthouse\lib\index.js:316:27
    at Generator.next (<anonymous>)
    at step (...\node_modules\penthouse\lib\index.js:45:191)
CRITICAL CSS ERROR Error: AST parser (css-tree) found 12 errors in CSS.
    Breaking because in strict mode.
    The first error was:
    Parse error: RightParenthesis is expected
    1 |…led]{cursor:not-allowed;opacity:.65;filter:alpha(opacity=65);box-shadow:none}a.btn.disabled{pointe…
----------------------------------------------------------------^
```

**Comment by pocketjoso** [comment]
The strict mode is.. strict, and not necessary to recommended to use (anymore). Yes, this css is invalid, and will most likely just be dropped by browsers - but the critical css generation will work despite this so you don't have to worry!
