### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by josenobile** [pocketjoso/penthouse#245]
Hello,  
When using penthouse from critical with several dimensions/resolutions (10)  I got an error related to https://github.com/GoogleChrome/puppeteer/issues/1873

Error: read ECONNRESET
    at TCP.onread (net.js:599:25)
Emitted 'error' event at:
    at WebSocket.finalize (.../node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:182:41)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
micro: Accepting connections on port 8282
events.js:165
      throw er; // Unhandled 'error' event
      ^
Looks like using this https://github.com/latesh/puppeteer-pool, could prevent the error.

**Comment by pocketjoso** [comment]
Hi @josenobile,
There's no need to ever launch more than one puppeteer (browser); it's more efficient to just open more tabs in the same browser instead. This is what Penthouse does automatically for concurrent jobs (since V1 when puppeteer was introduced). While pooling browser instances is not needed, a setup with something like a pool _of browser tabs_ can be, to prevent crashes like the one you mentioned. Nothing is built into penthouse for this at this time, but [it's very easy to setup yourself](https://github.com/pocketjoso/penthouse/blob/master/examples/many-urls.js).

However you're using critical, so you don't have that control - the question is instead then how critical uses Penthouse. I recently asked @bezoerb this question, [here](https://github.com/pocketjoso/penthouse/pull/244#issuecomment-371285940).

**Comment by pocketjoso** [comment]
Okay, so seems like something crashes chrome when too many tabs get opened at the same time, and you say you don't think it is RAM. What OS are you running on? What node version?

Since you are using critical you cannot do any kind of browser tab pooling yourself, it has to come from critical or penthouse. I've been thinking it could make sense to implement and by default use a simple pool inside Penthouse, perhaps capping the number of concurrent urls processed to ~5.

**Comment by pocketjoso** [comment]
Closing due to inactivity - just comment if you want to continue the discussion and I will re-open.
